### ISSUE TITLE
No such executable file: /usr/bin/php

### ISSUE THREAD

**Issue by misha-tgshv** [thang-nm/Google-Translate.popclipext#3]
When added to Popclip, an error occurs 
![](https://d.pr/i/GGQOXu+.jpg)

MacOS #Monterey, 12.0.1
PopClip, 2021.11 (1003785)

**Comment by thang-nm** [comment]
Hmm. PHP has been removed in macOS Monterey.
You can install it from Homebrew. ([Guide](https://wpbeaches.com/updating-to-php-versions-7-4-and-8-on-macos-12-monterey/))
After you install PHP, you need run this to link php to /usr/bin/php: `ln -s $(which php) /usr/bin/php`

**Comment by thang-nm** [comment]
Just moved from PHP to Ruby.
